name: 'dhis2: verify (app)'

on: push

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    D2_VERBOSE: true



jobs:
    install:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - name: Install
              if: steps.yarn-cache.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile

    build:
        runs-on: ubuntu-latest
        needs: install
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - name: Build
              run: yarn build

            - uses: actions/upload-artifact@v2
              with:
                  name: app-build
                  path: |
                      **/build
                      !**/node_modules
                  retention-days: 1

    lint:
        runs-on: ubuntu-latest
        needs: install
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - uses: actions/cache@v2
              id: yarn-cache
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

            - name: Generate translations
              run: yarn d2-app-scripts i18n generate

            - name: Lint
              run: yarn lint

    # test:
    #     runs-on: ubuntu-latest
    #     needs: install
    #     if: "!contains(github.event.head_commit.message, '[skip ci]')"
    #     steps:
    #         - uses: actions/checkout@v2
    #         - uses: actions/setup-node@v1
    #           with:
    #               node-version: 16.x

    #         - uses: actions/cache@v2
    #           id: yarn-cache
    #           with:
    #               path: '**/node_modules'
    #               key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

    #         - name: Generate translations
    #           run: yarn d2-app-scripts i18n generate

    #         - name: Test
    #           run: yarn test --passWithNoTests

    #e2e:
    #    runs-on: ubuntu-latest
    #    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    #    needs: [install]
    #
    #    strategy:
    #        matrix:
    #            containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    #
    #    steps:
    #        - name: Checkout
    #          uses: actions/checkout@v2
    #
    #        - uses: actions/setup-node@v1
    #          with:
    #              node-version: 16.x
    #
    #        - uses: actions/cache@v2
    #          id: yarn-cache
    #          with:
    #              path: '**/node_modules'
    #              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    #
    #        - name: Install Cypress binary
    #          run: yarn cypress install
    #
    #        - name: End-to-End tests
    #          uses: cypress-io/github-action@v2
    #          with:
    #              install: false
    #              record: true
    #              parallel: true
    #              start: ${{ env.SERVER_START_CMD }}
    #              wait-on: ${{ env.SERVER_URL }}
    #              wait-on-timeout: 300
    #              cache-key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    #              group: 'e2e'
    #              tag: ${{ github.event_name }}
    #          env:
    #              CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    #              COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
    #              STORYBOOK_TESTING: true
    #              SERVER_START_CMD: 'yarn cy:server'
    #              SERVER_URL: 'http://localhost:5001'

    # publish:
    #     runs-on: ubuntu-latest
    #     needs: [build, lint] # add e2e and/or test if you use it
    #     if: "!contains(github.event.head_commit.message, '[skip ci]')"
    #     steps:
    #         - uses: actions/checkout@v2
    #           with:
    #               token: ${{env.GH_TOKEN}}

    #         - uses: actions/setup-node@v1
    #           with:
    #               node-version: 16.x

    #         - uses: actions/download-artifact@v2
    #           with:
    #               name: app-build

    #         - uses: dhis2/deploy-build@master
    #           with:
    #               # uncomment following line for monorepo apps:
    #               #cwd: ./packages/app
    #               build-dir: build/app
    #               github-token: ${{ env.GH_TOKEN }}

    release:
        runs-on: ubuntu-latest
        needs: [build, lint, test] # add e2e if you use it
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'

            - uses: actions/download-artifact@v2
              with:
                  name: app-build

            # ensure that d2-app-scripts is available
            - run: yarn install --frozen-lockfile

            - uses: dhis2/action-semantic-release@master
              with:
                  publish-apphub: true
                  publish-github: true
                  github-token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
                  apphub-token: ${{ secrets.DHIS2_BOT_APPHUB_TOKEN }}

            - uses: dhis2/deploy-build@master
              with:
                  # uncomment following line for monorepo apps:
                  #cwd: ./packages/app
                  build-dir: build/app
                  github-token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

